### ISSUE TITLE
Possible small issue

### ISSUE THREAD

**Issue by esmeraldaliaj** [sebh/UnrealEngineSkyAtmosphere#10]
In order to have the project built using SDK v10 and Toolset v142, I had to include `#include <string>` in **Dx11Device.h**.

**Comment by sebh** [comment]
[Fixed!](https://github.com/sebh/UnrealEngineSkyAtmosphere/commit/f675c23ee16ef84bcbd3b314d4280c8f24c953b7)
And also fixed in my Dx11Base framework,
Thanks!
