### ISSUE TITLE
Render Error when viewing in space

### ISSUE THREAD

**Issue by lvvvmd** [sebh/UnrealEngineSkyAtmosphere#13]
![image](https://user-images.githubusercontent.com/26196355/183873043-fda2db26-809a-4fb0-8979-f6431a876353.png)
only ViewHeight and forward are changed.

**Comment by lvvvmd** [comment]
OK, Fixed. WorldDir loses precision when camera view is very large.
![image](https://user-images.githubusercontent.com/26196355/184054083-bfb0e2c8-e752-425a-a1b0-713796c688fd.png)
![image](https://user-images.githubusercontent.com/26196355/184054283-efaa7682-eea5-4bd8-ba47-f0c71787dfdc.png)

**Comment by sebh** [comment]
Thanks @lvvvmd , I could not reproduce but it is better to do in camera space anyway so I did apply the fix.
