### ISSUE TITLE
Something is wrong with repo setup

### ISSUE THREAD

**Issue by s0501007** [sebh/UnrealEngineSkyAtmosphere#5]
git submodule update --init does nothing.
I assume something is wrong with repo setup.
Maybe something like this:
https://stackoverflow.com/questions/39765663/git-submodule-init-does-absolutely-nothing

Not critical because it is possible to manually clone imgui and tinyexr.

**Comment by sebh** [comment]
Thanks for reporting: this should now be fixed on latest.
